apiVersion: v1
kind: ConfigMap
metadata:
  name: ecol-configmap
  namespace: default
data:
  IMAGEPATH: /app/docxletters/routes/
  FILEPATH: /app/nfs/demandletters
  DB_USER: ecol
  DB_PASSWORD: ecol
  CONNECTIONSTRING: 192.168.0.30:1521/ORCLCDB.localdomain
  